### ISSUE TITLE
Try with this...

### ISSUE THREAD

**Issue by carduz** [jmt-improved/arrowsjs#1]
```ES6
var complexMatrix = [
    [-1,-1,0,-1, 0, 0, 0],
    [-1,-1,0,-1, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
    [0,0,0,0, 0, 0, 0],
];

var complexLines = [
    [[0,4],[6,0]],
    [[2,3],[3,0]]
];

```

**Comment by ImperiumMaximus** [comment]
The algorithm converges although there are no components in the neighbor cells where the two lines end.
Note that for proper drawing, an additional matrix that explains which components are physically connected to a line is required otherwise in the case there are two (or more) components in the neighbor cells of a starting (ending) point of a line, using current data structures, it is impossible to distinguish between the actual connected component and the others.
